### ISSUE TITLE
Trigger idea: A task was assigned to an account

### ISSUE THREAD

**Issue by Rosey** [flowapp/zapier-flow#24]

**Comment by alibosworth** [comment]
Ideally this would trigger regardless of if it was assigned during task creation or after, right?

**Comment by Rosey** [comment]
right, which I think would be easy to do with polling, if we are getting with owner_id param, sorted by updated_at, anything new added should be caught 🤔 We may want to paginate though.

**Comment by Rosey** [comment]
I can think of some edge cases where if someone modifies an older task assigned to you it may not have previously been on page 1.  So paginating might be good.

**Comment by alibosworth** [comment]
I wonder if paginating with small page sizes will be the best way to keep the api implications low, along with requesting "updated since", because if you imagine x hundred people setting up polling triggers multiplied by happening every 3 minutes...

**Comment by Rosey** [comment]
Totally.

**Comment by Rosey** [comment]
Even if we don't know exactly when zapier last checked, if we set an updated_after of the last `hour` I think that would be a large enough window. Maybe we should do that with all our task requests!

**Comment by josiahwiebe** [comment]
I started using [Rest Hooks](http://resthooks.org/) with some of our APIs. This helps to reduce the overhead of polling triggers. This would be a change that would have to be made in your API code, but if you're going to be focusing on integrations at all in the future, it's well worth taking a look at.

**Comment by Rosey** [comment]
Thanks! Yeah we definitely should. There's a few things we want to improve with the API to make things easier/better - adding oauth support instead of relying on using a token being another.

buuuut we also have all kinds of stuff on our roadmap for API and a pretty small team so we'll see 🙃

**Comment by Rosey** [comment]
We were discussing this in slack and this can be achieved via filters, so perhaps this is not necessary to add.
