### ISSUE TITLE
Switch Accounts to use Roles instead of Memberships

### ISSUE THREAD

**Issue by Rosey** [flowapp/zapier-flow#6]
Not currently exposed by the public API but when it is, we should switch over. Memberships only works if an account is a member of at least one workspace, but it is possible to have an account that has access to Chat but no workspaces. In addition, you can have multiple membership models for a single account. The Roles endpoint is a more accurate representation of accounts in an organization.

🤔 I actually wonder if we should the accounts feature until support for this is added, since it could cause behaviour that users may think is a bug?

**Comment by alibosworth** [comment]
> 🤔 I actually wonder if we should the accounts feature until support for this is added, since it could cause behaviour that users may think is a bug?

I think waiting on roles support sounds like it is probably wise.

**Comment by Rosey** [comment]
Yeah, cool. Let's do that then.

**Comment by Rosey** [comment]
Did that for now here https://github.com/flowapp/zapier-flow/pulls
